service: lambda-edge-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

package:
  individually: true
  patterns:
    # - '!**/**'
    - '!package-testing/**'
    - '!venv/**'
    - '!node_modules/**'
    - '!pkg/**'

functions:
  viewerRequest:
    handler: viewer_request.handler
    module: rootFunc1

  originResponse:
    handler: origin_response.handler
    module: rootFunc2

  # viewerRequest:
  #   handler: viewer_request.handler
  #   module: src/image_service/viewer_request
  
  # originResponse:
  #   handler: origin_response.handler
  #   module: src/image_service/origin_response

  # viewerRequest:
  #   handler: src/service/viewer_request.handler
  #   package:
  #     patterns:
  #       - 'src/service/viewer_request.py'
  
  # originResponse:
  #   handler: src/service/origin_response.handler
  #   package:
  #     patterns:
  #       - 'src/service/origin_response.py'

plugins:
  - serverless-python-requirements
  - serverless-localstack
  - serverless-plugin-scripts

custom:
  localstack:
    stages:
      - local
  
  scripts:
    hooks:
      'package:finalize': ./foo.sh


  # pythonRequirements:
  #   dockerizePip: true
  